import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Header";
import { Mulish } from "next/font/google";
import Footer from "./component/Footer";

const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={mulish.className} >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
